### ISSUE TITLE
TEMPDIR is not set

### ISSUE THREAD

**Issue by Bagu** [palinkas-jo-reggelt/hMailServer_CatchSpam#2]
Hi,

It seem that TEMPDIR in eventhandler, line 131 is not set because it throw an error (for me at least)
If i set it by `Private Const TEMPDIR = "D:\hMailServer\Events"` (for my install) it work without error.

**Comment by palinkas-jo-reggelt** [comment]
oops. You are correct. That's missing. Thanks for letting me know.
