### ISSUE TITLE
Error: 800A01F4 - Description: Variable non définie: 'PTR_Record'

### ISSUE THREAD

**Issue by Bagu** [palinkas-jo-reggelt/hMailServer_CatchSpam#3]
https://github.com/palinkas-jo-reggelt/hMailServer_CatchSpam/blob/4487c2b55e729f4fa8ba3b943649eca0775fd13d/EventHandlers.vbs#L239

I get Error: 800A01F4 - Description: Variable non définie: 'PTR_Record'
Maybe it should be modified from :
`Dim strRegEx, Match, Matches`

To : 
`Dim strRegEx, Match, Matches, PTR_Record`

**Comment by palinkas-jo-reggelt** [comment]
Got it. Thanks.
