### ISSUE TITLE
Missing semi colon

### ISSUE THREAD

**Issue by Bagu** [palinkas-jo-reggelt/hMailServer_CatchSpam#4]
Hello,

https://github.com/palinkas-jo-reggelt/hMailServer_CatchSpam/blob/341b331aef01479781d984457821ef28cfcfff31/www/stylesheet.css#L118

Plus, border-spacing work only if border-collapse is set to separate.
If border-collapseis set to collapse, then, border-spacing is not applied.

Is it desired to set `border-spacing: 10px;` with `border-collapse: collapse;` ?

**Comment by palinkas-jo-reggelt** [comment]
> Is it desired to set `border-spacing: 10px;` with `border-collapse: collapse;` ?

¯\_(ツ)_/¯ I'm not an expert with css. I messed around with it until it gave me the result I wanted. There are probably other issues with it too. Most browsers are pretty forgiving on stuff like this. My focus was really on _catching spam_. :-)

I added the missing semi-colon. Thanks.

**Comment by Bagu** [comment]
No problem ;)
I'm not an expert too.
I tried to add a space between the domain name and the table border.
And i see the missing semi colon while i tried to change this ;)
